### ISSUE TITLE
[Problema] Checkout transparente

### ISSUE THREAD

**Issue by vbrazo** [moiplabs/moip-ruby#11]
O suporte de vocês me mandou as seguintes sugestões de melhoria:

Para fazer isso daqui, teríamos que modificar a sua gem visto que a sua gem é da moip.

Abaixo a descrição do e-mail que eu recebi deles:

Atualizado por: Integração, 19 Set 15:43 (BRT):
Vitor boa tarde,

Informamos que no seu XML está incorreto, pois tem a tag de pagamento direto, e esta ferramenta foi descontinuada e não é mais ativada, portanto retire esta tag, apenas utilizamos a integração transparente, não pagamento direto.

Outro erro no XML, a parcela, um erro muito comum no envio deste tipo de instrução, é difinir a TAG "MinimoParcelas" com o valor "1", ficando:<MinimoParcelas>1</MinimoParcelas>, pois a tag "Parcelamento" (presente dentro da Tag <Parcelamentos>)possui duas Tag's dentro de si que definem o número Minimo e Maximo de parcelas, no caso <MinimoParcelas></MinimoParcelas> e <MaximoParcelas></MaximoParcelas>, porem o valor "1" em "MinimoParcelas" não tem efeito algum.

O correto é:

(Exemplo): <Parcelamentos>
<Parcelamento>
<MinimoParcelas>2</MinimoParcelas>
<MaximoParcelas>15</MaximoParcelas>
</Parcelamento>
</Parcelamentos>

Informamos que a homologação foi concluída com sucesso, nos informe o login Moip por gentileza.

Atenciosamente,

Integração
Moip | Suporte Avançado e Integração

Moip. Tudo o que você precisa em pagamentos online

**Comment by Irio** [comment]
@vbrazo Te aconselharia a usar a https://github.com/Irio/mymoip se for usar Checkout Transparente. Tu tem controle total sobre os requests sem stress.
